import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryClient = new QueryClient();
  return (
    <html lang="en">
      {/* <QueryClientProvider client={queryClient}> */}
      <body className={inter.className}>
        {/* <div className="w-full relative">
          <Header />
        </div> */}
        <div className="flex">
          {/* <div className="w-24 h-screen ">
            <Navbar />
          </div> */}
          <div>{children}</div>
        </div>
      </body>
      {/* </QueryClientProvider> */}
    </html>
  );
}
