import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryClient = new QueryClient();
  return (
    <html lang="en">
      <Head>
        <title>Your Website</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      {/* <QueryClientProvider client={queryClient}> */}
      <body className="md:w-[1640px] w-[890px]">
        {/* <div className="w-full relative">
          <Header />
        </div> */}
        <div className="flex">
          {/* <div className="w-24 h-screen ">
            <Navbar />
          </div> */}
          <div>{children}</div>
        </div>
      </body>
      {/* </QueryClientProvider> */}
    </html>
  );
}
